### ISSUE TITLE
Cannot run the plugin - No virtual method getNoBackupFilesDir

### ISSUE THREAD

**Issue by rfesty** [Swrve/swrve-sdk-integrations#7]
Hi,

First, there is a line that prevents from the plugin to compile on Android if you have different package name
import com.phonegap.helloworld.Application 22 (SwrvePlugin.java) 

After removing the line, it threw an error: Multiple dex files define 
I've resolved that by updating the support library to the latest.

Now I get:
java.lang.RuntimeException Caused by: java.lang.NoSuchMethodError: No virtual method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.exmaple.hello-1/base.apk)

Which I can't solve in any way,
Any help will be appreciated
Thanks!

**Comment by Sergio-Mira** [comment]
Hi @rfesty thanks for letting us know about that line! It has been removed.
That last error, does your build target match the version of the support library you are using now?

**Comment by rfesty** [comment]
Hi @Sergio-Mira, thanks for your response!
It does match, We updated the support to the latest version. This is the plugin gradle file now:
repositories {
    jcenter{
        url = 'http://dl.bintray.com/swrve-inc/android'
    }
}

android {
    lintOptions {
        abortOnError false
    }
}

dependencies {
    compile ('com.swrve.sdk.android:swrve-google:4.3.0'){
		exclude module: 'support-v4'

	}
    compile 'com.android.support:support-v13:23.2.0'
}

the "exclude module" seemed to fixe the "Multiple dex files define" error and it complies.

After the app starts, it throws the "No virtual method getNoBackupFilesDir" exception

**Comment by Sergio-Mira** [comment]
I believe that v13 does not include all the v4 classes. You could try instead of excluding the module adding the specific version that your app requires of the support library (that all need to be the same):

compile 'com.android.support:support-v4:23.2.0'

Let me know how it goes

**Comment by Sergio-Mira** [comment]
And these properties need to match too:
```
android {
    compileSdkVersion 23
    buildToolsVersion '23.2.0'
}
```

**Comment by rfesty** [comment]
I keep getting:

 ```
FATAL EXCEPTION: AsyncTask #2
                                                 Process: com.undertap.prankerprankcallfunny, PID: 2961
                                                 java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                     at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.NoSuchMethodError: No virtual method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.undertap.prankerprankcallfunny-1/base.apk)
                                                     at com.google.android.gms.iid.zzd.zzeb(Unknown Source)
                                                     at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                     at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                     at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                                                     at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                                                     at com.swrve.sdk.Swrve$2.doInBackground(Swrve.java:164)
                                                     at com.swrve.sdk.Swrve$2.doInBackground(Swrve.java:142)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

this is my the plugin's gradle now:
```
repositories {
    jcenter{
        url = 'http://dl.bintray.com/swrve-inc/android'
    }
}

android {
    lintOptions {
        abortOnError false
    }
    compileSdkVersion 23
    buildToolsVersion '23.2.0'
}

dependencies {
    compile 'com.swrve.sdk.android:swrve-google:4.3.0'
    compile 'com.android.support:support-v4:23.2.0'
}

```

**Comment by Sergio-Mira** [comment]
Those changes should be done the app build.gradle instead. Modifying the plugin might make it difficult to update later on.

Could you run 'gradle dependencies'? All points to a version mismatch between some of the support libs

**Comment by rfesty** [comment]
Thanks, @Sergio-Mira, I'm getting:

```
+--- com.swrve.sdk.android:swrve-google:4.3.0
|    +--- com.swrve.sdk.android:swrve-common:4.3.0
|    +--- com.swrve.sdk.android:swrve-conversations:4.3.0
|    |    +--- com.google.code.gson:gson:2.2.+ -> 2.2.4
|    |    +--- com.android.support:appcompat-v7:23.+ -> 23.2.0
|    |    |    +--- com.android.support:animated-vector-drawable:23.2.0
|    |    |    |    \--- com.android.support:support-vector-drawable:23.2.0
|    |    |    \--- com.android.support:support-vector-drawable:23.2.0
|    |    \--- com.swrve.sdk.android:swrve-common:4.3.0
|    +--- com.google.code.gson:gson:2.2.+ -> 2.2.4
|    +--- com.android.support:appcompat-v7:23.+ -> 23.2.0 (*)
|    +--- com.google.android.gms:play-services-gcm:8.4.0
|    |    +--- com.google.android.gms:play-services-base:8.4.0
|    |    |    \--- com.google.android.gms:play-services-basement:8.4.0
|    |    \--- com.google.android.gms:play-services-measurement:8.4.0
|    |         \--- com.google.android.gms:play-services-basement:8.4.0
|    \--- com.google.android.gms:play-services-ads:8.4.0
|         \--- com.google.android.gms:play-services-basement:8.4.0
+--- project :CordovaLib
\--- project :phonegap-facebook-plugin:FacebookLib
     \--- project :CordovaLib
```

**Comment by Sergio-Mira** [comment]
Is it possible that you could run that in your app instead? If you don't want to share it have a look at any support lib that is not 23.2.0.

It might be that another plugin (reading on the net someone was having issues with a Facebook SDK plugin) is using an old support lib and there are different versions.

**Comment by rfesty** [comment]
Hi @Sergio-Mira 
That is my app folder (:

You are right about the facebook sdk, The same problem can be found [here](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1234#issuecomment-191435968)

Adding the following :
`configurations { all*.exclude group: 'com.android.support', module:
'support-v4' }`

allows it to compile but the "No virtual method getNoBackupFilesDir" exception remains.
Any thoughts of how to make both of them run together?

**Comment by Sergio-Mira** [comment]
Did you have a look at the demo we ship with the plugin?
Your PhoneGap app gradle changes should be done in the build-extras.gradle file:
https://github.com/Swrve/swrve-sdk-integrations/blob/master/PhoneGap/SwrvePhoneGapDemo/platforms/android/build-extras.gradle

There are some lines in there to force PhoneGap to use certain build tools:
```
ext.cdvBuildToolsVersion = '23.0.1'
ext.cdvCompileSdkVersion = 23
```

Maybe it might help? Have tried reproducing again here and haven't been able to.

**Comment by Sergio-Mira** [comment]
Looks like the Facebook PhoneGap SDK is built including an specific version of V4:
https://github.com/Wizcorp/phonegap-facebook-plugin/tree/master/platforms/android/FacebookLib/libs

**Comment by rfesty** [comment]
It works! adding the build-extras.gradle did the job
Thanks very much @Sergio-Mira
